name = "warehouse"
main = "src/index.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "WAREHOUSE_KV", id = "d396e7e64dfd48eb993f3b384c031b5f" }
]

[[r2_buckets]]
binding = "WAREHOUSE_R2"
bucket_name = "warehouse-docs"

[[d1_databases]]
binding = "NOTES_DB"
database_name = "warehouse-notes"
database_id = "f207d094-065f-4978-92f5-06d7fac6ae23"
